
services:
  auth0_mock:
    container_name: "${AUTH0_CONTAINER_NAME-auth0_mock}"
    stdin_open: true
    tty: true
    build:
      context: ./auth0_mock
      dockerfile: Dockerfile
    networks:
      devnet:
    command: yarn run start
    environment:
      NODE_ENV: dev
      DEBUG: nodejs-docker-express:*
      AUTH0_DOMAIN:
      AUTH0_AUDIENCE:
      AUTH0_DEFAULT_USER:
      AUTH0_DEFAULT_PASSWORD:
      AUTH0_ACCESS_TOKEN_EXP:
      AUTH0_ID_TOKEN_EXP:

networks:
  devnet:
    name: ${DEVNET_NAME-devnet}
    external: true
